// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package submate

import (
	"database/sql"
)

type Submate struct {
	ID          int64
	Identifier  sql.NullString
	Name        sql.NullString
	Description sql.NullString
}

type SubmateMember struct {
	ID        int64
	UserID    sql.NullInt64
	SubmateID sql.NullInt64
	Note      sql.NullString
}

type Subscription struct {
	ID        int64
	Name      sql.NullString
	SubmateID sql.NullInt32
}

type SubscriptionSubmateMember struct {
	SubscriptionID  sql.NullInt64
	SubmateMemberID sql.NullInt64
}

type User struct {
	ID        int64
	Username  sql.NullString
	Name      sql.NullString
	Bio       sql.NullString
	Email     string
	Password  string
	Avatar    sql.NullString
	Role      sql.NullString
	CreatedAt sql.NullTime
}
