// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: user.sql

package submate

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, name, bio, email, password, avatar, role, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, username, name, bio, email, avatar, role, created_at
`

type CreateUserParams struct {
	Username  sql.NullString
	Name      sql.NullString
	Bio       sql.NullString
	Email     string
	Password  string
	Avatar    sql.NullString
	Role      sql.NullString
	CreatedAt sql.NullTime
}

type CreateUserRow struct {
	ID        int64
	Username  sql.NullString
	Name      sql.NullString
	Bio       sql.NullString
	Email     string
	Avatar    sql.NullString
	Role      sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Bio,
		arg.Email,
		arg.Password,
		arg.Avatar,
		arg.Role,
		arg.CreatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Email,
		&i.Avatar,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, name, bio, email, password, avatar, role, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Email,
		&i.Password,
		&i.Avatar,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, name, bio, email, password, avatar, role, created_at FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Bio,
			&i.Email,
			&i.Password,
			&i.Avatar,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
